Add /disttocore
nthirtyone/avorion-scripts pull request #13
Opened 2017-02-20 07:35 UTC by Salminar

Disttocore v 1.1 final

2017-02-20 15:44 UTC, nthirtyone requested changes
With a command this simple it is hard to find anything wrong. But. It is missing `readme` entry.

Just add it (follow general pattern) and it should be good (if nobody notices anything else).

2017-02-21 18:36 UTC, wmark commented on README.md
> +Display the distance in sectors between the player and the center of the galaxy. Usage `/disttocore`
Display**s**

(no blocker, though)

2017-02-21 18:36 UTC, wmark commented on scripts/commands/disttocore.lua
> +    return 0, "", ""
Please use tabs only.

2017-02-21 18:36 UTC, wmark commented on scripts/player/cmd/disttocore.lua
> +	player:sendChatMessage("Server", 0, "Distance from core : "..math.ceil(distanceFromCenter*10)*.1)
`"Distance from \\s(0:0): "…`

A community could refer to the area encompassed by the *barrier* as the *core*, so using `(0:0)` as reference removes any confusion. (The markup `\\s(…:…)` will turn the coordinates into a link that, if clicked on it, opens the galaxy map.)

2017-08-13 00:16 UTC, merged

2017-08-13 00:16 UTC, nthirtyone commented
Merging, I will fix "issues" with upcoming changes.